---
- name: Install Docker on Ubuntu ARM64
  hosts: all
  become: yes

  vars:
    docker_apt_key_url: "https://download.docker.com/linux/ubuntu/gpg"
    docker_repository: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install prerequisite packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Create Docker keyring directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Add Docker’s official GPG key
      apt_key:
        url: "{{ docker_apt_key_url }}"
        keyring: /etc/apt/keyrings/docker.gpg
        state: present

    - name: Set up Docker repository
      apt_repository:
        repo: "{{ docker_repository }}"
        state: present

    - name: Update APT package index (after adding Docker repo)
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to Docker group (optional)
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      when: ansible_user != "root"
